spring:
  datasource:
    url: jdbc:mysql://database-1.cdko4482w9o2.ap-northeast-1.rds.amazonaws.com:3306/demo
    username: admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: aazs9872630@gmail.com
    password: oukm yons gxlp cirb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true